#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTCS2,          sensorI2CCustom)
#pragma config(Sensor, S3,     IRseeker,       sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "rdpartyrobotcdr-3.3.1\drivers\hitechnic-irseeker-v2.h"

int _dirAC = 0;
int acS1, acS2, acS3, acS4, acS5 = 0;
int maxSig = 0; 					// the max signal strength from the seeker.
// These are the tuning variables. Set these based on results of test runs.
int wrist_pos = 26;				// At the rack height.
int irGoal = 7;						// 25, 26Where is the beacon.
int irStrengthGoal = 115; // 100<x<125 the IR strenght goal (we are on the rack).
int turnTime = 145; ///// Time (ms) to complete 90 degree turn.
int beaconDirection = 2; ///// Which side of the robot is the beacon on (1=left, 2= right)?


void initializeRobot()
{
	servoChangeRate[servoWrist] =20;          // Slow the Servo Change Rate down to only 4 positions per update.
	servo[servoWrist] = wrist_pos;
}

void driveMotors(int lspeed, int rspeed)
{
	motor[motorL] = lspeed;
	motor[motorR] = rspeed;
}

void MovetoIR()
{
	while(true)
	{
		_dirAC = HTIRS2readACDir(IRseeker);
		nxtDisplayCenteredBigTextLine(1, "IR: %d", _dirAC);

		switch(beaconDirection)
		{
		case 2:
			if (_dirAC < irGoal)
			{
				driveMotors(100, 100);
			}

			if (_dirAC >= irGoal)
			{
				driveMotors(0, 0);
				wait1Msec(10);
				return;
				break;
			}
			break;
		case 1:
			if (_dirAC < irGoal)
			{
				driveMotors(100, 100);
			}

			if (_dirAC >= irGoal)
			{
				driveMotors(0, 0);
				wait1Msec(10);
				break;
			}
			break;
		}
	}
}
// Turn 90 degrees to the beaconDirection .
void Turn90()
{
	int turnSpeed = 75;
motor[motorL] = beaconDirection == 2 ? turnSpeed : -turnSpeed;
	motor[motorR] = -motor[motorL];
	wait10Msec(turnTime);
	motor[motorL] = 0;
	motor[motorR] = 0;
	nxtDisplayCenteredBigTextLine(2, "turnSpeed: %d",turnSpeed);
}

void MoveToRack()
{
	while(true)
	{
		HTIRS2readAllACStrength(IRseeker, acS1, acS2, acS3, acS4, acS5);
	maxSig = (acS1 > acS2) ? acS1 : acS2;
	maxSig = (maxSig > acS3) ? maxSig : acS3;
	maxSig = (maxSig > acS4) ? maxSig : acS4;
	maxSig = (maxSig > acS5) ? maxSig : acS5;
	nxtDisplayCenteredBigTextLine(3, "maxSig: %d", maxSig);
		if (maxSig < irStrengthGoal)
		{
			driveMotors(30, 30);
		}
		if (maxSig >= irStrengthGoal)
		{
			driveMotors(0, 0);
			wait1Msec(10);
			break;
		}
	}
}

task main()
{
	initializeRobot();
	//waitForStart();

	MovetoIR();
	Turn90();
	MoveToRack();
	servo[servoWrist] = 128;
	driveMotors(-25,-25);
	driveMotors(0,0);
	wait10Msec(1);

	PlaySound(soundFastUpwardTones);
}
