#pragma config(Sensor, S1,     HTCS2,          sensorI2CCustom)
#pragma config(Sensor, S2,     IRseeker,       sensorI2CCustom)
#pragma config(Motor,  motorA,          motorL,        tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,          motorR,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorGrab,     tmotorNXT, PIDControl)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.3.1\drivers\hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"
#include "rdpartyrobotcdr-3.3.1\drivers/hitechnic-colour-v2.h"

int turnTime = 145; ///// Time (ms) to complete 90 degree turn.
int beaconDirection = 2; ///// Which side of the robot is the beacon on (1=left, 2= right)?


void initializeRobot()
{
}

int getColor(int color)
{
	int red = 0;
	int green = 0;
	int blue = 0;
	int _color = 0;

	// Read the currently detected colour from the sensor
	_color = HTCS2readColor(HTCS2);
	if (!HTCS2readRGB(HTCS2, red, green, blue)) {
		nxtDisplayTextLine(4, "ERROR!!");
		wait1Msec(2000);
		StopAllTasks();
	}

	nxtDisplayCenteredTextLine(0, "Color: %d", _color);
	nxtDisplayCenteredBigTextLine(1, "R  G  B");

	nxtEraseRect(0,10, 99, 41);
	nxtFillRect( 0, 10, 30, 10 + (red+1)/8);
	nxtFillRect(35, 10, 65, 10 + (green+1)/8);
	nxtFillRect(70, 10, 99, 10 + (blue+1)/8);

	if (_color == color)
	{
		return 1;

	}
	else

	{
		return 0;
	}
}
void driveMotors(int lspeed, int rspeed)
{
	motor[motorL] = lspeed;
	motor[motorR] = rspeed;
}


void MoveForward ()
{
	driveMotors (25,25);
}

// Turn 90 degrees to the beaconDirection .
void Turn90()
{
	int turnSpeed = 75;
motor[motorL] = beaconDirection == 2 ? turnSpeed : -turnSpeed;
	motor[motorR] = -motor[motorL];
	wait10Msec(turnTime);
	motor[motorL] = 0;
	motor[motorR] = 0;
	nxtDisplayCenteredBigTextLine(2, "turnSpeed: %d",turnSpeed);
}


task main()
{
	int timesec=0;
	initializeRobot();
	//waitForStart();
	MoveForward ();

	 while (getColor(3) == 0)
	{
		wait10Msec (100) ;
		timesec+=1;
		if (timesec>3)
		{
			break;
		}
	}
	driveMotors(0,0);
}
