#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,          motorGrab,     tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRO,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorRA,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoLeft,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoRight,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                  Tele-Operation Mode
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define JOYSTICK_MIN 10
int wrist_pos=24;          //starting position for wrist servo

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                    initializeRobot
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	servoChangeRate[servoLeft] =1;          // Slow the Servo Change Rate down to only 4 positions per update.
	servo[servoLeft] = wrist_pos;                              // Move servo1 to position to starting position

	servoChangeRate[servoRight] =1;          // Slow the Servo Change Rate down to only 4 positions per update.
	servo[servoRight] = wrist_pos;                              // Move servo1 to position to starting position
}

//code to control the wheels, aka "driving"
void driveMotors()
{
	int joyLeft = joystick.joy1_y1;
	int joyRight = joystick.joy1_y2;

	if ((abs(joyLeft) > JOYSTICK_MIN) || (abs(joyRight) > JOYSTICK_MIN))
	{
		if (abs(joyLeft) < 80)
		{
			if (joyLeft > 0)
				joyLeft = 1*pow(1+.056,joyLeft);
			else
				joyLeft = -1*pow(1+.056,abs(joyLeft));
		}

		if (abs(joyRight) < 80)
		{
			if (joyRight > 0)
				joyRight = 1*pow(1+.056,joyRight);
			else
				joyRight = -1*pow(1+.056,abs(joyRight));
		}

		motor[motorL] = (joyLeft)*100/127;
		motor[motorR] = (joyRight)*100/127;
	}
	else
	{
		motor[motorL] = 0;
		motor[motorR] = 0;
	}
}

//SEVERE Servo Control EX-treme 2013!!!
void moveServos()
{
	int buttonValues = joystick.joy1_Buttons;
	int servoUp = buttonValues & 64;
	int servoDown = buttonValues & 16;
	int closeGrabber =  buttonValues & 32;
	int openGrabber = buttonValues & 128;

	if ((servoUp + servoDown + closeGrabber + openGrabber) == 0)
	{
		return;
	}

	if (servoUp && wrist_pos <= 255)
	{
		wrist_pos += 1;
	}

	if (servoDown && wrist_pos >= 0)
	{
		wrist_pos -= 1;
	}
	servo[servoLeft] = wrist_pos;

	servo[servoRight] = -wrist_pos;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                         Main Task
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

	initializeRobot();

	//waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);   // Obtain current game controller settings

		//Display Joystick Values for Testing - Not Used in Competition
		nxtDisplayString(0, "joy1_x1: %d", joystick.joy1_x1);
		nxtDisplayString(1, "joy1_y1: %d", joystick.joy1_y1);
		nxtDisplayString(2, "joy1_x2: %d", joystick.joy1_x2);
		nxtDisplayString(3, "joy1_y2: %d", joystick.joy1_y2);
		nxtDisplayString(4, "Buttons: %d", joystick.joy1_Buttons);
		nxtDisplayString(5, "TopHat:  %d", joystick.joy1_TopHat);

		// Drive Motors
		driveMotors();

		// Servos
		moveServos();

		// Rotate arm
		//rotateArm();

		// Raise or Lower arm
		//raiseArm();
	}
}
