#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  motorC,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoLeft,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoRight,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                  Tele-Operation Mode
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define JOYSTICK_MIN 10

//starting position for servos
int servo_pos1=24;
int servo_pos2=24;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                    initializeRobot
/////////////////////////////////////////////////////////////////////////////////////////////////////

//initializing robot, fix bugs and position servos, etc.. here
void initializeRobot()
{
	servo[servoLeft] = servo_pos1;                              // Move servo1 to position to starting position

	servo[servoRight] = servo_pos2;                              // Move servo1 to position to starting position
}

void moveServos()
{
	int buttonValues = joystick.joy1_Buttons;
	int servoUp = buttonValues & 16;
	int servoDown = buttonValues & 64;

	if ((servoUp + servoDown) == 0)
	{
		return;
	}

	if (servoUp <= 255)
	{
		servo_pos1 += 15;
		servo_pos2 += 15;
	}

	if (servoDown >= 0)
	{
		servo_pos1 -= 5;
		servo_pos2 -= 5;
	}
	servo[servoLeft] = servo_pos1;

	servo[servoRight] = servo_pos2;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                         Main Task
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

	initializeRobot();

	//waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);   // Obtain current game controller settings

		//Display Joystick Values for Testing - Not Used in Competition
		nxtDisplayString(0, "joy1_x1: %d", joystick.joy1_x1);
		nxtDisplayString(1, "joy1_y1: %d", joystick.joy1_y1);
		nxtDisplayString(2, "joy1_x2: %d", joystick.joy1_x2);
		nxtDisplayString(3, "joy1_y2: %d", joystick.joy1_y2);
		nxtDisplayString(4, "Buttons: %d", joystick.joy1_Buttons);
		nxtDisplayString(5, "TopHat:  %d", joystick.joy1_TopHat);

		// Servos
		moveServos();

	}
}
